### PR TITLE
Allow a a passed options.auth to be used instead of the token.

### PR DESCRIPTION
**Pull request by jacobian**
I need this so I can "log in" via the client (e.g. duplicate what `heroku login`
does); the workflow there is to hit `/ouath/authorizations` with a
username/password in basic auth, which then provides the oauth token to be used.

### CODE REVIEW

**Comment by jclem** [comment]
@jacobian Looks good to me, but I'm not sure who is maintaining this now. Want to merge this @JackCA?

**Comment by JackCA** [comment]
thanks @jacobian.

miss u @jclem

**Comment by zeke** [comment]
I miss you all and your J names.

**Comment by jclem** [comment]
sup

**Pull request merged**
