### PR TITLE
Update to include pipelines resources

### PR DESCRIPTION
**Pull request by appleton**
The pipelines api is now part of the mainline v3. I ran `bin/update` and got pipelines stuff as well as some other changes.

### CODE REVIEW

**Comment by appleton** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lJSq2Tb1&#x2F;1367-bump-cli-to-1-0-0"> Bump CLI to 1.0.0</a>

**Comment by appleton** [comment]
Ping @dickeyxxx I'd love to merge this and get it into the cli so we can do away with the [verbose calls](https://github.com/heroku/heroku-pipelines/blob/master/lib/api.js) in the pipelines plugin.

**Comment by dickeyxxx** [comment]
looking into why the tests are failing

**Comment by dickeyxxx** [comment]
not sure why it was failing before, but I fixed it now

**Pull request merged**
