### PR TITLE
simplified dependencies

### PR DESCRIPTION
**Pull request by dickeyxxx**
because we use this inside each CLI plugin, having many dependencies greatly increases the amount of space we need for the CLI. I took some time to remove packages are I think are not needed. This will require a major bump in the version number.

logfmt was easily removed by allowing the developer to set the `logger` attribute to an instance of `logfmt`.

concat-stream was simplified into a simple helper function.

lazy.js was replaced with the built-in `util._extend`

caching functionality was removed. I don't think any projects are using it anymore.

This takes the size of the node_modules folder from 2.9 meg down to 0.3 meg.

### CODE REVIEW

**Comment by dickeyxxx** [comment]
any thoughts on this @jmonster?

**Comment by sehrope** [comment]
> caching functionality was removed. I don't think any projects are using it anymore.

We use the caching feature though it's for a webapp not a CLI tool/plugin. We set a relatively low TTL for the cache entries but it's enough to handle the user clicking through quickly and definitely speeds things up.

Rather than removing it, is there a way to make it optional?

If you are going to remove it, you should update the TOC at the top of the README as well (it still has links to the sections you removed).

**Comment by dickeyxxx** [comment]
thanks for mentioning you're using it. I'll try to find a way to make it optional like I did the logger. It'll be a bit trickier though.

**Comment by zeke** [comment]
:+1:

**Comment by jmonster** [comment]
+ we aren't using redis on dashboard
+ in-memory caching is bad news bears since we're running not only on multiple dynos but multiple worker processes
+ I think in may circumstances this module can be replaced with vanilla node-request:

```js
let client = Bluebird.promisifyAll(Request.defaults({
  auth: { bearer: 'insert-bearer-token-here' },
  baseUrl: 'https://api.heroku.com/'
  headers: {
    'accept': 'application/vnd.heroku+json; version=3',
    'user-agent': 'my-heroku-client'
  },
  timeout: 5000,
  json: true,
  gzip: true
}));

client.get('/apps').then((apps) => {
  // do things with user's apps
});
```

**Comment by jmonster** [comment]
[my opinion no caching is specifically in the context of dashboard!]

**Comment by dickeyxxx** [comment]
@zeke @sehrope thanks for letting me know you'd still like the caching. I added it back into this pull request but in a way that won't require installing memjs and simple-encryptor for every client. Let me know what you think.

**Comment by dickeyxxx** [comment]
@jmonster thanks for doing some research. This did use memcache by default, so it isn't just in memory on a dyno. I'm not really arguing for you to put it back in though; I happen to like using request by itself like you show personally.

**Pull request merged**
